version: "3.9"

services:
  
  checkout-app:
    build: .
    container_name: checkout-app-local
    environment:
      TZ: America/Sao_Paulo
      SPRING_DATA_REDIS_HOST: redis-checkout
      SPRING_DATA_REDIS_PORT: 6379
    ports:
      - "8082:8080"
    depends_on:
      - redis-checkout
    networks:
      - checkout-network

  redis-checkout:
    container_name: checkout-redis-local
    image: redis
    ports:
        - "6380:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - checkout-network
  
  prometheus:
    container_name: checkout-prometheus-local
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9092:9090"
    networks:
      - checkout-network
  
  grafana:
    image: grafana/grafana:latest
    container_name: checkout-grafana-local
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_FEATURE_TOGGLES_ENABLE=accesscontrol
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3002:3000"
    depends_on:
      - prometheus
    networks:
      - checkout-network

networks:
  checkout-network:
    driver: bridge