global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "account-service"
    static_configs:
      - targets: ["account-app:8080"]
        labels:
          application: "account"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s

  - job_name: "checkout-service"
    static_configs:
      - targets: ["checkout-app:8080"]
        labels:
          application: "checkout"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s

  - job_name: "stock-service"
    static_configs:
      - targets: ["stock-app:8080"]
        labels:
          application: "stock"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s

  - job_name: "order-service"
    static_configs:
      - targets: ["order-app:8080"]
        labels:
          application: "order"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s

  - job_name: "payment-service"
    static_configs:
      - targets: ["payment-app:8080"]
        labels:
          application: "payment"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s