version: "3.9"

services:

  account-app:
    build: .
    container_name: account-app-local
    environment:
      TZ: America/Sao_Paulo
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres-account:5432/accountdb
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: postgres
    ports:
      - "8081:8080"
    depends_on:
      - postgres-account
    networks:
      - account-network

  postgres-account:
    container_name: account-postgres-local
    image: postgres:17
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: accountdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - account-network

  prometheus:
    container_name: account-prometheus-local
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    networks:
      - account-network

  grafana:
    image: grafana/grafana:latest
    container_name: account-grafana-local
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_FEATURE_TOGGLES_ENABLE=accesscontrol
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    networks:
      - account-network

networks:
  account-network:
    driver: bridge